import { DashboardSidebar } from '@/components/dashboard/DashboardSidebar';
import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
      <body suppressHydrationWarning>
        <main className='flex min-h-screen'>
            <DashboardSidebar/>
           <div className='flex-1'> {children}</div>
        </main>
      </body>
  );
}
